### ISSUE TITLE
issue with bug fixing related to max_value

### ISSUE THREAD

**Issue by JaishreeJaishankar** [jiny2001/dcscn-super-resolution#42]
train.py raises an type error for load_batch_image() method in DCSCN.py .Removing the self.max_value parameter solves the issue in training.
![image](https://user-images.githubusercontent.com/13587219/43460621-c5036e74-94ee-11e8-9ced-5ceee5e17f9d.png)

**Comment by jiny2001** [comment]
Oops, thank you to let me know.
I was working on the other branch and now merge it to main branch. I believe now the error is resolved.

**Comment by JaishreeJaishankar** [comment]
Hi,
Not yet ,the issue isn't resolved.The train.py code still raises the error.Removing max_value still works but probably its in use in an other file.

**Comment by jiny2001** [comment]
Oops, thank you to let me know. Will check it again soon.

**Comment by jiny2001** [comment]
Sorry, I always use build_btach=True option and the error is happening when build_btach=False.
Please use the latest one.

**Comment by JaishreeJaishankar** [comment]
Heya,
It's working fine now :)
